pages:
  -
    title: "About"
    seo_content: "About, Update this area"
    slug: "about"
    group_name: "about"
    sub_group_name: "overview"
    position: 2
    group_root: true
    body: !xml |
      <h1>About</h1>
  -
    title: "Staff"
    seo_content: "Staff, Update this area"
    slug: "about/staff"
    group_name: "about"
    sub_group_name: "staff"
    position: 1
    body: !xml |
      <div class="row no-gutter">
        <div class="col-sm-10 col-sm-offset-1">
          <img src="http://gm-s3-qa.intridea.com/documents/attachments/000/000/005/original/staff-hero.png?1443624976" class="img-responsive">
        </div>
      </div>
      <div class="row">
        <div class="col-sm-10 col-sm-offset-1">
          <ul class="nav nav-tabs" id="staff-tabs">
            <li role="presentation" class="active"><a href="/about/staff">Staff</a></li>
            <li role="presentation" class=""><a href="/about/trustees">Trustees</a></li>
          </ul>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-10 col-sm-offset-1">
          <h5 class="margin-top margin-bottom-xl">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</h5>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-10 col-sm-offset-1">
          <div class="row">
            <div class="col-sm-6 col-md-3">
              <div class="thumbnail">
                <img src="http://greatminds.net/maps/images/staff/munson.jpg" alt="" class="img-circle" data-toggle="modal" data-target="#bio1">
                <div class="caption">
                  <h3>Lynne Munson</h3>
                  <p><em>President and Executive Director</em></p>
                  <div class="modal fade" id="bio1">
                    <div class="modal-dialog">
                      <div class="modal-content">
                        <div class="modal-header">
                          <h4 class="modal-title">Bio</h4>
                        </div>
                        <div class="modal-body">
                          <p>Donec mi odio, faucibus at, scelerisque quis, convallis in, nisi. Nunc interdum lacus sit amet orci. Integer ante arcu, accumsan a, consectetuer eget, posuere ut, mauris. Ut non enim eleifend felis pretium feugiat. Ut tincidunt tincidunt erat.</p>
                          <p>Donec mi odio, faucibus at, scelerisque quis, convallis in, nisi. Nunc interdum lacus sit amet orci. Integer ante arcu, accumsan a, consectetuer eget, posuere ut, mauris. Ut non enim eleifend felis pretium feugiat. Ut tincidunt tincidunt erat.</p>
                        </div>
                        <div class="modal-footer">
                          <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-sm-6 col-md-3">
              <div class="thumbnail">
                <img src="http://greatminds.net/maps/images/staff/kevin_shane.jpg" alt="" class="img-circle" data-toggle="modal" data-target="#bio2">
                <div class="caption">
                  <h3>Kevin Shane</h3>
                  <p><em>Director of Human Capital</em></p>
                  <div class="modal fade" id="bio2">
                    <div class="modal-dialog">
                      <div class="modal-content">
                        <div class="modal-header">
                          <h4 class="modal-title">Bio</h4>
                        </div>
                        <div class="modal-body">
                          <p>Donec mi odio, faucibus at, scelerisque quis, convallis in, nisi. Nunc interdum lacus sit amet orci. Integer ante arcu, accumsan a, consectetuer eget, posuere ut, mauris. Ut non enim eleifend felis pretium feugiat. Ut tincidunt tincidunt erat.</p>
                          <p>Donec mi odio, faucibus at, scelerisque quis, convallis in, nisi. Nunc interdum lacus sit amet orci. Integer ante arcu, accumsan a, consectetuer eget, posuere ut, mauris. Ut non enim eleifend felis pretium feugiat. Ut tincidunt tincidunt erat.</p>
                        </div>
                        <div class="modal-footer">
                          <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-sm-6 col-md-3">
              <div class="thumbnail">
                <img src="http://greatminds.net/maps/images/staff/jill.jpg" alt="" class="img-circle" data-toggle="modal" data-target="#bio3">
                <div class="caption">
                  <h3>Jill Diniz</h3>
                  <p><em>Director of Eureka Math</em></p>
                  <div class="modal fade" id="bio3">
                    <div class="modal-dialog">
                      <div class="modal-content">
                        <div class="modal-header">
                          <h4 class="modal-title">Bio</h4>
                        </div>
                        <div class="modal-body">
                          <p>Donec mi odio, faucibus at, scelerisque quis, convallis in, nisi. Nunc interdum lacus sit amet orci. Integer ante arcu, accumsan a, consectetuer eget, posuere ut, mauris. Ut non enim eleifend felis pretium feugiat. Ut tincidunt tincidunt erat.</p>
                          <p>Donec mi odio, faucibus at, scelerisque quis, convallis in, nisi. Nunc interdum lacus sit amet orci. Integer ante arcu, accumsan a, consectetuer eget, posuere ut, mauris. Ut non enim eleifend felis pretium feugiat. Ut tincidunt tincidunt erat.</p>
                        </div>
                        <div class="modal-footer">
                          <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-sm-6 col-md-3">
              <div class="thumbnail">
                <img src="http://greatminds.net/maps/images/staff/natanya-staff.jpg" alt="" class="img-circle" data-toggle="modal" data-target="#bio4">
                <div class="caption">
                  <h3>Natanya Levioff</h3>
                  <p><em>Director of Program Operations and Support</em></p>
                  <div class="modal fade" id="bio4">
                    <div class="modal-dialog">
                      <div class="modal-content">
                        <div class="modal-header">
                          <h4 class="modal-title">Bio</h4>
                        </div>
                        <div class="modal-body">
                          <p>Donec mi odio, faucibus at, scelerisque quis, convallis in, nisi. Nunc interdum lacus sit amet orci. Integer ante arcu, accumsan a, consectetuer eget, posuere ut, mauris. Ut non enim eleifend felis pretium feugiat. Ut tincidunt tincidunt erat.</p>
                          <p>Donec mi odio, faucibus at, scelerisque quis, convallis in, nisi. Nunc interdum lacus sit amet orci. Integer ante arcu, accumsan a, consectetuer eget, posuere ut, mauris. Ut non enim eleifend felis pretium feugiat. Ut tincidunt tincidunt erat.</p>
                        </div>
                        <div class="modal-footer">
                          <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-sm-6 col-md-3">
              <div class="thumbnail">
                <img src="http://greatminds.net/maps/images/staff/sarah-1.jpg" alt="" class="img-circle" data-toggle="modal" data-target="#bio5">
                <div class="caption">
                  <h3>Sarah Woodard</h3>
                  <p><em>Associate Director, English &amp; History</em></p>
                  <div class="modal fade" id="bio5">
                    <div class="modal-dialog">
                      <div class="modal-content">
                        <div class="modal-header">
                          <h4 class="modal-title">Bio</h4>
                        </div>
                        <div class="modal-body">
                          <p>Donec mi odio, faucibus at, scelerisque quis, convallis in, nisi. Nunc interdum lacus sit amet orci. Integer ante arcu, accumsan a, consectetuer eget, posuere ut, mauris. Ut non enim eleifend felis pretium feugiat. Ut tincidunt tincidunt erat.</p>
                          <p>Donec mi odio, faucibus at, scelerisque quis, convallis in, nisi. Nunc interdum lacus sit amet orci. Integer ante arcu, accumsan a, consectetuer eget, posuere ut, mauris. Ut non enim eleifend felis pretium feugiat. Ut tincidunt tincidunt erat.</p>
                        </div>
                        <div class="modal-footer">
                          <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
  -
    title: "Trustees"
    seo_content: "Trustees, Update this area"
    slug: "about/trustees"
    group_name: "about"
    sub_group_name: "trustees"
    position: 1
    body: !xml |
      <div class="row no-gutter">
        <div class="col-sm-10 col-sm-offset-1">
          <img src="http://gm-s3-qa.intridea.com/documents/attachments/000/000/005/original/staff-hero.png?1443624976" class="img-responsive">
        </div>
      </div>
      <div class="row">
        <div class="col-sm-10 col-sm-offset-1">
          <ul class="nav nav-tabs" id="staff-tabs">
            <li role="presentation" class=""><a href="/about/staff">Staff</a></li>
            <li role="presentation" class="active"><a href="/about/trustees">Trustees</a></li>
          </ul>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-10 col-sm-offset-1">
          <h5 class="margin-top margin-bottom-xl">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</h5>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-10 col-sm-offset-1">
          <div class="row">
            <div class="col-sm-6 col-md-3">
              <div class="thumbnail">
                <img src="http://greatminds.net/maps/images/staff/munson.jpg" alt="" class="img-circle">
                <div class="caption">
                  <h3>Lynne Munson</h3>
                  <p><em>President and Executive Director</em></p>
                  <button class="btn btn-default" data-toggle="collapse" data-target="#bioMunson">Bio</button>
                  <div class="collapse" id="bioMunson">
                    Lipsum
                  </div>
                </div>
              </div>
            </div>
            <div class="col-sm-6 col-md-3">
              <div class="thumbnail">
                <img src="http://greatminds.net/maps/images/staff/kevin_shane.jpg" alt="" class="img-circle">
                <div class="caption">
                  <h3>Kevin Shane</h3>
                  <p><em>Director of Human Capital</em></p>
                </div>
              </div>
            </div>
            <div class="col-sm-6 col-md-3">
              <div class="thumbnail">
                <img src="http://greatminds.net/maps/images/staff/jill.jpg" alt="" class="img-circle">
                <div class="caption">
                  <h3>Jill Diniz</h3>
                  <p><em>Director of Eureka Math</em></p>
                </div>
              </div>
            </div>
            <div class="col-sm-6 col-md-3">
              <div class="thumbnail">
                <img src="http://greatminds.net/maps/images/staff/natanya-staff.jpg" alt="" class="img-circle">
                <div class="caption">
                  <h3>Natanya Levioff</h3>
                  <p><em>Director of Program Operations and Support</em></p>
                </div>
              </div>
            </div>
            <div class="col-sm-6 col-md-3">
              <div class="thumbnail">
                <img src="http://greatminds.net/maps/images/staff/sarah-1.jpg" alt="" class="img-circle">
                <div class="caption">
                  <h3>Sarah Woodard</h3>
                  <p><em>Associate Director, English &amp; History<em></p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
