pages:
  -
    title: "Overview"
    seo_content: "History, Update this area"
    slug: "history"
    group_name: "history"
    sub_group_name: "overview"
    position: 1
    group_root: true
    body: !xml |
      <section id="background-grey" class="intro jumbo-text">
        <div class="page-header container">
          <h1>History Overview Page</h1>
          <h3 class="sub-head">Welcome to the Alexandria Plan Page</h3>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras sed sapien quam. Sed dapibus est id enim facilisis, at posuere turpis adipiscing. Quisque sit amet dui dui.</p>
          <a class="btn btn-primary" href="../marketing/product.html" role="button">Learn More</a>
        </div>
      </section>
      <section>
       <div class="container callout">
        <div id="viewport" class="row">
          <div class="col-xs-6">
           <h2>Intro into Maps</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
            tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
            quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
            consequat.</p>
           <a class="btn btn-primary" href="../marketing/product.html" role="button">Learn More</a>
           <a class="btn btn-default" href="#" role="button">Secondary CTA</a>
          </div>
          <div class="col-xs-1"></div>
          <div class="col-xs-5">
            <img src="../assets/img/fpo-image.jpg" class="img-thumbnail" alt="Responsive image">
          </div>
        </div>
        <hr>
        </div>
      </section>
      <section>
      <div class="container">
        <div id="viewport" class="row callout">
          <div class="col-xs-5">
            <img src="../assets/img/fpo-image.jpg" class="img-thumbnail" alt="Responsive image">
          </div>
          <div class="col-xs-1"></div>
          <div class="col-xs-6">
           <h2>Maps Section</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
            tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
            quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
            consequat.</p>
           <a class="btn btn-primary" href="../marketing/product.html" role="button">Learn More</a>
           <a class="btn btn-default" href="#" role="button">Secondary CTA</a>
          </div>
        </div>
        <hr>
        </div>
      </section>
      <section>
      <div class="container">
        <div id="viewport" class="row">
          <div class="col-xs-6">
           <h2>Training Section</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
            tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
            quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
            consequat.</p>
           <a class="btn btn-primary" href="../marketing/product.html" role="button">Learn More</a>
           <a class="btn btn-default" href="#" role="button">Secondary CTA</a>
          </div>
          <div class="col-xs-1"></div>
          <div class="col-xs-5">
            <img src="../assets/img/fpo-image.jpg" class="img-thumbnail" alt="Responsive image">
          </div>
        </div>
        <hr>
        </div>
      </section>
      <section class="bottom-space">
      <div class="container">
        <div id="viewport" class="row callout">
          <div class="col-xs-5 bottom-space">
            <img src="../assets/img/fpo-image.jpg" class="img-thumbnail" alt="Responsive image">
          </div>
          <div class="col-xs-1"></div>
          <div class="col-xs-6">
           <h2>Resources</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
            tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
            quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
            consequat.</p>
           <a class="btn btn-primary" href="../marketing/product.html" role="button">Learn More</a>
           <a class="btn btn-default" href="#" role="button">Secondary CTA</a>
          </div>
        </div>
        </div>
      </section>

  -
    title: "Admins"
    seo_content: "History Admins, Update this area"
    slug: "history/admins"
    group_name: "history"
    sub_group_name: "admins"
    position: 2
    body: !xml |
      <section id="background-grey" class="intro jumbo-text">
        <div class="page-header container">
          <h1>History Admin Page</h1>
          <h3 class="sub-head">Intro to Admin Page</h3>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras sed sapien quam. Sed dapibus est id enim facilisis, at posuere turpis adipiscing. Quisque sit amet dui dui.</p>
          <a class="btn btn-primary" href="../../marketing/product.html" role="button">Learn More</a>
        </div>
      </section>
      <section>
       <div class="container callout">
        <div id="viewport" class="row">
          <div class="col-xs-6">
           <h2>Maps Section Admin Specific</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
            tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
            quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
            consequat.</p>
           <a class="btn btn-primary" href="../../marketing/product.html" role="button">Learn More</a>
           <a class="btn btn-default" href="#" role="button">Secondary CTA</a>
          </div>
          <div class="col-xs-1"></div>
          <div class="col-xs-5">
            <img src="../../assets/img/fpo-image.jpg" class="img-thumbnail" alt="Responsive image">
          </div>
        </div>
        <hr>
        </div>
      </section>
      <section>
      <div class="container">
        <div id="viewport" class="row callout">
          <div class="col-xs-5">
            <img src="../../assets/img/fpo-image.jpg" class="img-thumbnail" alt="Responsive image">
          </div>
          <div class="col-xs-1"></div>
          <div class="col-xs-6">
           <h2>Training Section Admin Specific</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
            tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
            quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
            consequat.</p>
           <a class="btn btn-primary" href="../../marketing/product.html" role="button">Learn More</a>
           <a class="btn btn-default" href="#" role="button">Secondary CTA</a>
          </div>
        </div>
        <hr>
        </div>
      </section>
      <section>
      <div class="container bottom-space">
        <div id="viewport" class="row">
          <div class="col-xs-6 bottom-space">
           <h2>Resource Section Admin Specific</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
            tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
            quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
            consequat.</p>
           <a class="btn btn-primary" href="../../marketing/product.html" role="button">Learn More</a>
           <a class="btn btn-default" href="#" role="button">Secondary CTA</a>
          </div>
          <div class="col-xs-1"></div>
          <div class="col-xs-5">
            <img src="../../assets/img/fpo-image.jpg" class="img-thumbnail" alt="Responsive image">
          </div>
        </div>
        </div>
      </section>

  -
    title: "Teachers"
    seo_content: "History Teachers, Update this area"
    slug: "history/teachers"
    group_name: "history"
    sub_group_name: "teachers"
    position: 3
    body: !xml |
      <section id="background-grey" class="intro jumbo-text">
        <div class="page-header container">
          <h1>History Teacher Page</h1>
          <h3 class="sub-head">Intro to Teacher Page</h3>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras sed sapien quam. Sed dapibus est id enim facilisis, at posuere turpis adipiscing. Quisque sit amet dui dui.</p>
          <a class="btn btn-primary" href="../../marketing/product.html" role="button">Learn More</a>
        </div>
      </section>
      <section>
       <div class="container callout">
        <div id="viewport" class="row">
          <div class="col-xs-6">
           <h2>Maps Section Teacher Specific</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
            tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
            quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
            consequat.</p>
           <a class="btn btn-primary" href="../../marketing/product.html" role="button">Learn More</a>
           <a class="btn btn-default" href="#" role="button">Secondary CTA</a>
          </div>
          <div class="col-xs-1"></div>
          <div class="col-xs-5">
            <img src="../../assets/img/fpo-image.jpg" class="img-thumbnail" alt="Responsive image">
          </div>
        </div>
        <hr>
        </div>
      </section>
      <section>
      <div class="container">
        <div id="viewport" class="row callout">
          <div class="col-xs-5">
            <img src="../../assets/img/fpo-image.jpg" class="img-thumbnail" alt="Responsive image">
          </div>
          <div class="col-xs-1"></div>
          <div class="col-xs-6">
           <h2>Training Section Teacher Specific</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
            tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
            quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
            consequat.</p>
           <a class="btn btn-primary" href="../../marketing/product.html" role="button">Learn More</a>
           <a class="btn btn-default" href="#" role="button">Secondary CTA</a>
          </div>
        </div>
        <hr>
        </div>
      </section>
      <section>
      <div class="container bottom-space">
        <div id="viewport" class="row">
          <div class="col-xs-6 bottom-space">
           <h2>Resource Section Teacher Specific</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
            tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
            quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
            consequat.</p>
           <a class="btn btn-primary" href="../../marketing/product.html" role="button">Learn More</a>
           <a class="btn btn-default" href="#" role="button">Secondary CTA</a>
          </div>
          <div class="col-xs-1"></div>
          <div class="col-xs-5">
            <img src="../../assets/img/fpo-image.jpg" class="img-thumbnail" alt="Responsive image">
          </div>
        </div>
        </div>
      </section>

  -
    title: "Parents "
    seo_content: "History Parents, Update this area"
    slug: "history/parents"
    group_name: "history"
    sub_group_name: "parents"
    position: 4
    body: !xml |
      <section id="background-grey" class="intro jumbo-text">
        <div class="page-header container">
          <h1>History Parents Page</h1>
          <h3 class="sub-head">Intro to Parents Page</h3>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras sed sapien quam. Sed dapibus est id enim facilisis, at posuere turpis adipiscing. Quisque sit amet dui dui.</p>
          <a class="btn btn-primary" href="../../marketing/product.html" role="button">Learn More</a>
        </div>
      </section>
      <section>
       <div class="container callout">
        <div id="viewport" class="row">
          <div class="col-xs-6">
           <h2>Child Help Section Parent Specific</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
            tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
            quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
            consequat.</p>
           <a class="btn btn-primary" href="../../marketing/product.html" role="button">Learn More</a>
           <a class="btn btn-default" href="#" role="button">Secondary CTA</a>
          </div>
          <div class="col-xs-1"></div>
          <div class="col-xs-5">
            <img src="../../assets/img/fpo-image.jpg" class="img-thumbnail" alt="Responsive image">
          </div>
        </div>
        <hr>
        </div>
      </section>
      <section class="bottom-space">
      <div class="container">
        <div id="viewport" class="row callout">
          <div class="col-xs-5 bottom-space">
            <img src="../../assets/img/fpo-image.jpg" class="img-thumbnail" alt="Responsive image">
          </div>
          <div class="col-xs-1"></div>
          <div class="col-xs-6">
           <h2>Resource Section Parent Specific</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
            tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
            quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
            consequat.</p>
           <a class="btn btn-primary" href="../../marketing/product.html" role="button">Learn More</a>
           <a class="btn btn-default" href="#" role="button">Secondary CTA</a>
          </div>
        </div>
        </div>
      </section>

  -
    title: "Alexandria Shop"
    seo_content: "History Alexandria Shop, Update this area"
    slug: "history/eureka-shop"
    group_name: "history"
    sub_group_name: "alexandria-shop"
    position: 5
    body: !xml |
      <section>
        <div class="page-header container container-secondary">
        <h1>History Store Page</h1>
        <ul class="filter">
          <h3>FILTERS:</h3>
          <li>Price ▼</li>
          <li>Medium ▼</li>
          <li>Curriculum ▼</li>
        </ul>
      </div>
      </section>
      <section class="callout bottom-space">
      <div class="container">
        <div class="row">
          <div id="dashboard" class="col-xs-12 bottom-space">
            <h2>History materials</h2>
            <div class="col-xs-4">
              <h4>Curriculum</h4>
              <div class="checkbox">
                <label>
                  <input type="checkbox"> Item
                </label>
              </div>
              <div class="checkbox">
                <label>
                  <input type="checkbox"> Item
                </label>
              </div>
              <div class="checkbox">
                <label>
                  <input type="checkbox"> Item
                </label>
              </div>
              <div class="checkbox">
                <label>
                  <input type="checkbox"> Item
                </label>
              </div>
              <div class="checkbox">
                <label>
                  <input type="checkbox"> Item
                </label>
              </div>
             <a class="btn btn-primary" href="../cart.html" role="button">Add to Cart</a>
            </div>

            <div class="col-xs-4">
              <h4>Books</h4>
                <div class="checkbox">
                  <label>
                    <input type="checkbox"> Item
                  </label>
                </div>
                <div class="checkbox">
                  <label>
                    <input type="checkbox"> Item
                  </label>
                </div>
                <div class="checkbox">
                  <label>
                    <input type="checkbox"> Item
                  </label>
                </div>
                <a class="btn btn-primary" href="../cart.html" role="button">Add to Cart</a>
            </div>

            <div class="col-xs-4">
              <h4>Videos</h4>
              <div class="checkbox">
                  <label>
                    <input type="checkbox"> Item
                  </label>
                </div>
                <div class="checkbox">
                  <label>
                    <input type="checkbox"> Item
                  </label>
                </div>
                <div class="checkbox">
                  <label>
                    <input type="checkbox"> Item
                  </label>
                </div>
                <a class="btn btn-primary" href="../cart.html" role="button">Add to Cart</a>
            </div>
          </div>
        </div>
      </div></section>
