pages:
  -
    title: "Overview"
    seo_content: "History, Update this area"
    slug: "history"
    group_name: "history"
    sub_group_name: "overview"
    position: 1
    group_root: true
    tiles:
      :rows:
        -
          rowType: 'Full Width Text'
          title: 'History Overview Page'
          body_text: !xml |
            <h3 class="sub-head">Welcome to the Wheatley History Page</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras sed sapien quam. Sed dapibus est id enim facilisis, at posuere turpis adipiscing. Quisque sit amet dui dui.</p>
          background_color: 'cream'
          button_title: 'Learn More'
          button_link: '/english'
          position: 0

        -
          rowType: '50/50 Full-Bleed Image Left'
          title: 'Intro into Curriculum'
          body_text: !xml |
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
            tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
            quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
            consequat.</p>
          image_url: ''
          background_color: 'green'
          button_1_title: 'Learn More'
          button_1_link: '/english'
          button_2_title: 'Secondary CTA'
          button_2_link: '/english'
          position: 1

        -
          rowType: '50/50 Full-Bleed Image Right'
          title: 'Curriculum Section'
          body_text: !xml |
            <p>
              Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
            </p>
          image_url: ''
          background_color: 'cream'
          button_title: 'Learn More'
          button_link: '/english'
          position: 2

  -
    title: "Teachers"
    seo_content: "History Teachers, Update this area"
    slug: "history/teachers"
    group_name: "history"
    sub_group_name: "teachers"
    position: 2
    tiles:
      :rows:
        -
          rowType: 'Full Width Text'
          title: 'History Teacher Page'
          body_text: !xml |
            <h3 class="sub-head">Intro to teacher Page</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras sed sapien quam. Sed dapibus est id enim facilisis, at posuere turpis adipiscing. Quisque sit amet dui dui.</p>
          background_color: 'cream'
          button_title: 'Learn More'
          button_link: '/english'
          position: 0

        -
          rowType: '50/50 Full-Bleed Image Left'
          title: 'Intro into Curriculum'
          body_text: !xml |
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
            tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
            quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
            consequat.</p>
          image_url: ''
          background_color: 'green'
          button_1_title: 'Learn More'
          button_1_link: '/english'
          button_2_title: 'Secondary CTA'
          button_2_link: '/english'
          position: 1

        -
          rowType: '50/50 Full-Bleed Image Right'
          title: 'Curriculum Section'
          body_text: !xml |
            <p>
              Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
            </p>
          image_url: ''
          background_color: 'cream'
          button_title: 'Learn More'
          button_link: '/english'
          position: 2

  -
    title: "Parents"
    seo_content: "History Parents, Update this area"
    slug: "history/parents"
    group_name: "history"
    sub_group_name: "parents"
    position: 3
    body: !xml |
    tiles:
      :rows:
        -
          rowType: 'Full Width Text'
          title: 'History Parent Page'
          body_text: !xml |
            <h3 class="sub-head">Intro to parent Page</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras sed sapien quam. Sed dapibus est id enim facilisis, at posuere turpis adipiscing. Quisque sit amet dui dui.</p>
          background_color: 'cream'
          button_title: 'Learn More'
          button_link: '/english'
          position: 0

        -
          rowType: '50/50 Full-Bleed Image Left'
          title: 'Intro into Curriculum'
          body_text: !xml |
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
            tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
            quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
            consequat.</p>
          image_url: ''
          background_color: 'green'
          button_1_title: 'Learn More'
          button_1_link: '/english'
          button_2_title: 'Secondary CTA'
          button_2_link: '/english'
          position: 1

        -
          rowType: '50/50 Full-Bleed Image Right'
          title: 'Curriculum Section'
          body_text: !xml |
            <p>
              Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
            </p>
          image_url: ''
          background_color: 'cream'
          button_title: 'Learn More'
          button_link: '/english'
          position: 3

  -
    title: "Admins"
    seo_content: "History Admins, Update this area"
    slug: "history/admins"
    group_name: "history"
    sub_group_name: "admins"
    position: 4
    tiles:
      :rows:
        -
          rowType: 'Full Width Text'
          title: 'History Admins Page'
          body_text: !xml |
            <h3 class="sub-head">Intro to admins Page</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras sed sapien quam. Sed dapibus est id enim facilisis, at posuere turpis adipiscing. Quisque sit amet dui dui.</p>
          background_color: 'cream'
          button_title: 'Learn More'
          button_link: '/english'
          position: 0

        -
          rowType: '50/50 Full-Bleed Image Left'
          title: 'Intro into Curriculum'
          body_text: !xml |
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
            tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
            quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
            consequat.</p>
          image_url: ''
          background_color: 'green'
          button_1_title: 'Learn More'
          button_1_link: '/english'
          button_2_title: 'Secondary CTA'
          button_2_link: '/english'
          position: 1

        -
          rowType: '50/50 Full-Bleed Image Right'
          title: 'Curriculum Section'
          body_text: !xml |
            <p>
              Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
            </p>
          image_url: ''
          background_color: 'cream'
          button_title: 'Learn More'
          button_link: '/english'
          position: 3

  -
    title: "Alexandria Shop"
    seo_content: "History Alexandria Shop, Update this area"
    slug: "history/eureka-shop"
    group_name: "history"
    sub_group_name: "alexandria-shop"
    position: 5
    body: !xml |
      <section>
        <div class="page-header container container-secondary">
        <h1>History Store Page</h1>
        <ul class="filter">
          <h3>FILTERS:</h3>
          <li>Price ▼</li>
          <li>Medium ▼</li>
          <li>Curriculum ▼</li>
        </ul>
      </div>
      </section>
      <section class="callout bottom-space">
      <div class="container">
        <div class="row">
          <div id="dashboard" class="col-xs-12 bottom-space">
            <h2>History materials</h2>
            <div class="col-xs-4">
              <h4>Curriculum</h4>
              <div class="checkbox">
                <label>
                  <input type="checkbox"> Item
                </label>
              </div>
              <div class="checkbox">
                <label>
                  <input type="checkbox"> Item
                </label>
              </div>
              <div class="checkbox">
                <label>
                  <input type="checkbox"> Item
                </label>
              </div>
              <div class="checkbox">
                <label>
                  <input type="checkbox"> Item
                </label>
              </div>
              <div class="checkbox">
                <label>
                  <input type="checkbox"> Item
                </label>
              </div>
             <a class="btn btn-primary" href="../cart.html" role="button">Add to Cart</a>
            </div>

            <div class="col-xs-4">
              <h4>Books</h4>
                <div class="checkbox">
                  <label>
                    <input type="checkbox"> Item
                  </label>
                </div>
                <div class="checkbox">
                  <label>
                    <input type="checkbox"> Item
                  </label>
                </div>
                <div class="checkbox">
                  <label>
                    <input type="checkbox"> Item
                  </label>
                </div>
                <a class="btn btn-primary" href="../cart.html" role="button">Add to Cart</a>
            </div>

            <div class="col-xs-4">
              <h4>Videos</h4>
              <div class="checkbox">
                  <label>
                    <input type="checkbox"> Item
                  </label>
                </div>
                <div class="checkbox">
                  <label>
                    <input type="checkbox"> Item
                  </label>
                </div>
                <div class="checkbox">
                  <label>
                    <input type="checkbox"> Item
                  </label>
                </div>
                <a class="btn btn-primary" href="../cart.html" role="button">Add to Cart</a>
            </div>
          </div>
        </div>
      </div></section>
