pages:
  -
    title: "Greatminds"
    seo_content: "greatminds"
    slug: "/"
    group_name: "home"
    sub_group_name: ""
    position: 0
    body: !xml |
      <div class="row intro masthead" style="background-image: url('http://gm-s3-qa.intridea.com/documents/attachments/000/000/020/original/homepage-masthead.jpg?1443038050')">
        <div class="col-xs-12 masthead-content text-center">
          <h5 class="home-mast-intro bold"><span class="green-text">Every</span> child is capable of <span class="green-text">greatness</span></h5>
          <div id="pageSelection">
            <div class="btn-group fixed-width image-background">
              <button class="btn btn-default btn-block-xs margin-sm-bottom-m dropdown-toggle" type="button" id="dropdownRole" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                I am a
                <span class="caret"></span>
              </button>
              <ul class="dropdown-menu" aria-labelledby="dropdownRole">
                <li><a href="#">Teacher</a></li>
                <li><a href="#">Parent</a></li>
                <li><a href="#">Administrator</a></li>
              </ul>
            </div>
            <div class="btn-group fixed-width image-background">
              <button class="btn btn-default btn-block-xs margin-sm-bottom-m dropdown-toggle" type="button" id="dropdownCurriculum" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                Looking into
                <span class="caret"></span>
              </button>
              <ul class="dropdown-menu" aria-labelledby="dropdownCurriculum">
                <li><a href="#">Math</a></li>
                <li><a href="#">English</a></li>
                <li><a href="#">History</a></li>
              </ul>
            </div>
            <a href="#" id="btnGo" class="btn btn-default btn-transparent btn-block-xs margin-sm-bottom-m" disabled="disabled">Go</a>
          </div>
        </div>
      </div>

      <section class="row green-bg">
        <div class="col-sm-6 col-centered-content">
          <div class="vertical-center">
            <h6 class="bold">Lorem ipsum dolor sit amet</h6>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
            tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
            quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
            consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
            cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
            proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
            <a class="btn btn-default btn-block-xs" href="footer_nav/about.html">Learn More</a>
          </div>
        </div>
        <div class="col-sm-6 col-img-full" style="background-image: url('http://gm-s3-qa.intridea.com/documents/attachments/000/000/014/original/homepage-content1.png?1442491419')">
        </div>
      </section>

      <section class="row cream-bg">
        <div class="col-sm-6 col-centered-content">
          <div class="vertical-center">
            <img src="http://gm-s3-qa.intridea.com/documents/attachments/000/000/013/original/homepage-book.png?1442491391" class="img-responsive img-book margin-sm-bottom-xl" />
          </div>
        </div>
        <div class="col-sm-6 col-centered-content">
          <div class="vertical-center">
            <h6 class="bold">Lorem ipsum dolor sit amet</h6>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
            tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
            quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
            consequat.</p>
            <a class="btn btn-default btn-block-xs" href="main_nav/contact.html">Learn More</a>
          </div>
        </div>
      </section>

      <section class="row blue-bg">
        <div class="col-sm-6 col-img-full" style="background-image: url('http://gm-s3-qa.intridea.com/documents/attachments/000/000/015/original/homepage-content2.png?1442491440')">
        </div>
        <div class="col-sm-6 col-centered-content">
          <div class="vertical-center">
            <h6 class="bold">Lorem ipsum dolor sit amet</h6>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
            tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
            quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
            consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
            cillum dolore eu fugiat nulla pariatur.</p>
            <a class="btn btn-default btn-block-xs margin-bottom-m" href="footer_nav/about.html">Learn More</a>
            <a class="btn btn-default btn-block-xs margin-bottom-m" href="footer_nav/about.html">Download</a>
          </div>
        </div>
      </section>
