pages:
  -
    title: "Greatminds"
    seo_content: "greatminds"
    slug: "/"
    group_name: "home"
    sub_group_name: ""
    position: 0
    tiles:
      :rows:
        -
          rowType: 'Role/Curriculum Selector Hero'
          title: '<h5 class="home-mast-intro bold"><span class="green-text">Every</span> child is capable of <span class="green-text">greatness</span></h5>'
          background_image_url: 'http://gm-s3-qa.intridea.com/documents/attachments/000/000/020/original/homepage-masthead.jpg?1443038050'
          position: 0
        -
          rowType: '50/50 Full-Bleed Image Right'
          title: 'Lorem ipsum dolor sit amet'
          body_text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
      tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
      quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
      consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
      cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
      proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'
          button_title: 'Learn More'
          button_link: '/'
          background_color: 'green'
          image_url: 'http://gm-s3-qa.intridea.com/documents/attachments/000/000/014/original/homepage-content1.png?1442491419'
          position: 1
        -
          rowType: '50/50 Full-Bleed Image Left'
          title: 'Lorem ipsum dolor sit amet'
          body_text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
      tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
      quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
      consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
      cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
      proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'
          button_1_title: 'Learn More'
          button_1_link: '/'
          button_2_title: ''
          button_2_link: ''
          background_color: 'cream'
          image_url: 'http://gm-s3-qa.intridea.com/documents/attachments/000/000/013/original/homepage-book.png?1442491391'
          position: 1
        -
          rowType: '50/50 Full-Bleed Image Left'
          title: 'Lorem ipsum dolor sit amet'
          body_text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
      tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
      quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
      consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
      cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
      proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'
          button_1_title: 'Learn More'
          button_1_link: '/'
          button_2_title: 'Download'
          button_2_link: '/'
          background_color: 'blue'
          image_url: 'http://gm-s3-qa.intridea.com/documents/attachments/000/000/015/original/homepage-content2.png?1442491440'
          position: 1
