pages:
  -
    title: 'Overview'
    seo_content: 'Math, Update this area'
    slug: 'math'
    group_name: "math"
    sub_group_name: "overview"
    position: 1
    show_in_nav: true
    show_in_footer: false
    group_root: true
    tiles:
      :rows:
        -
          rowType: 'Video Hero'
          title: 'Lorem ipsum dolor sit amet'
          video_url: 'http://gm-s3-qa.intridea.com/documents/attachments/000/000/011/original/eureka-math-hd.mp4?1442330466'
          background_image_url: 'http://gm-s3-qa.intridea.com/documents/attachments/000/000/018/original/mathpage-videobackground1.jpg?1443029702'
          position: 0

        -
          rowType: 'Full Width Text'
          title: 'Lorem ipsum dolor sit amet'
          body_text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras sed sapien quam. Sed dapibus est id enim facilisis, at posuere turpis adipiscing. Quisque sit amet dui dui.'
          background_color: 'green'
          button_title: 'Learn More'
          button_link: '/Math'
          position: 1

        -
          rowType: 'Image Background, Text Left'
          title: 'Lorem ipsum dolor sit amet'
          body_text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'
          button_title: 'Learn More'
          button_link: '/math'
          image_url: 'http://gm-s3-qa.intridea.com/documents/attachments/000/000/008/original/mathpage-content1.jpg?1442330362'
          position: 2

        -
          rowType: '3-Column Text'
          background_color: 'cream'
          title_1: 'Lorem ipsum dolor sit amet'
          body_text_1: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.'
          button_title_1: 'Learn More'
          button_link_1: '/math'
          title_2: 'Lorem ipsum dolor sit amet'
          body_text_2: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.'
          button_title_2: 'Learn More'
          button_link_2: '/math'
          title_3: 'Lorem ipsum dolor sit amet'
          body_text_3: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.'
          button_title_3: 'Learn More'
          button_link_3: '/math'
          position: 3

        -
          rowType: 'Image Background, Text Left'
          title: 'Lorem ipsum dolor sit amet'
          body_text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'
          button_title: 'Learn More'
          button_link: '/math'
          image_url: 'http://gm-s3-qa.intridea.com/documents/attachments/000/000/010/original/mathpage-content2.jpg?1442330393'
          position: 4

        -
          rowType: '2-Column Text'
          background_color_1: 'cream'
          title_1: 'Lorem ipsum dolor sit amet'
          body_text_1: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.'
          button_title_1: 'Learn More'
          button_link_1: '/math'
          background_color_2: 'blue'
          title_2: 'Lorem ipsum dolor sit amet'
          body_text_2: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.'
          button_title_2: 'Learn More'
          button_link_2: '/math'
          position: 5

        -
          rowType: 'Image Background, Full Width Text'
          title: 'Lorem ipsum dolor sit amet'
          body_text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'
          button_title: 'Learn More'
          button_link: '/math'
          image_url: 'http://gm-s3-qa.intridea.com/documents/attachments/000/000/010/original/mathpage-content2.jpg?1442330393'
          position: 6

  -
    title: 'Teachers'
    seo_content: 'Math Teachers, Update this area'
    slug: 'math/teachers'
    group_name: "math"
    sub_group_name: "teachers"
    position: 2
    show_in_nav: true
    show_in_footer: false
    group_root: false
    tiles:
      :rows:
        -
          rowType: 'Full Width Text'
          title: 'Math Admins Page'
          body_text: !xml |
            <h3 class="sub-head">Intro to admins Page</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras sed sapien quam. Sed dapibus est id enim facilisis, at posuere turpis adipiscing. Quisque sit amet dui dui.</p>
          background_color: 'cream'
          button_title: 'Learn More'
          button_link: '/english'
          position: 0

        -
          rowType: '50/50 Full-Bleed Image Left'
          title: 'Intro into Curriculum'
          body_text: !xml |
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
            tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
            quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
            consequat.</p>
          image_url: ''
          background_color: 'green'
          button_1_title: 'Learn More'
          button_1_link: '/english'
          button_2_title: 'Secondary CTA'
          button_2_link: '/english'
          position: 1

        -
          rowType: '50/50 Full-Bleed Image Right'
          title: 'Curriculum Section'
          body_text: !xml |
            <p>
              Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
            </p>
          image_url: ''
          background_color: 'cream'
          button_title: 'Learn More'
          button_link: '/english'
          position: 3

  -
    title: "Parents "
    seo_content: "Math Parents, Update this area"
    slug: "math/parents"
    group_name: "math"
    sub_group_name: "parents"
    position: 3
    tiles:
      :rows:
        -
          rowType: 'Full Width Text'
          title: 'Math Parent Page'
          body_text: !xml |
            <h3 class="sub-head">Intro to parent Page</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras sed sapien quam. Sed dapibus est id enim facilisis, at posuere turpis adipiscing. Quisque sit amet dui dui.</p>
          background_color: 'cream'
          button_title: 'Learn More'
          button_link: '/english'
          position: 0

        -
          rowType: '50/50 Full-Bleed Image Left'
          title: 'Intro into Curriculum'
          body_text: !xml |
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
            tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
            quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
            consequat.</p>
          image_url: ''
          background_color: 'green'
          button_1_title: 'Learn More'
          button_1_link: '/english'
          button_2_title: 'Secondary CTA'
          button_2_link: '/english'
          position: 1

        -
          rowType: '50/50 Full-Bleed Image Right'
          title: 'Curriculum Section'
          body_text: !xml |
            <p>
              Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
            </p>
          image_url: ''
          background_color: 'cream'
          button_title: 'Learn More'
          button_link: '/english'
          position: 3

  -
    title: 'Admins'
    seo_content: 'Math Admins, Update this area'
    slug: 'math/admins'
    group_name: "math"
    sub_group_name: "admins"
    position: 4
    show_in_nav: true
    show_in_footer: false
    group_root: false
    tiles:
      :rows:
        -
          rowType: 'Full Width Text'
          title: 'History Admins Page'
          body_text: !xml |
            <h3 class="sub-head">Intro to admins Page</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras sed sapien quam. Sed dapibus est id enim facilisis, at posuere turpis adipiscing. Quisque sit amet dui dui.</p>
          background_color: 'cream'
          button_title: 'Learn More'
          button_link: '/english'
          position: 0

        -
          rowType: '50/50 Full-Bleed Image Left'
          title: 'Intro into Curriculum'
          body_text: !xml |
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
            tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
            quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
            consequat.</p>
          image_url: ''
          background_color: 'green'
          button_1_title: 'Learn More'
          button_1_link: '/english'
          button_2_title: 'Secondary CTA'
          button_2_link: '/english'
          position: 1

        -
          rowType: '50/50 Full-Bleed Image Right'
          title: 'Curriculum Section'
          body_text: !xml |
            <p>
              Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
            </p>
          image_url: ''
          background_color: 'cream'
          button_title: 'Learn More'
          button_link: '/english'
          position: 3
