---
engines:
  brakeman:
    enabled: false
  bundler-audit:
    enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
      - scss
  eslint:
    enabled: true
  fixme:
    enabled: false
  rubocop:
    enabled: true
  reek:
    enabled: false
  scss-lint:
    enabled: false
ratings:
  paths:
  - Gemfile.lock
  - "**.erb"
  - "**.haml"
  - "**.rb"
  - "**.rhtml"
  - "**.slim"
  - "**.scss"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
exclude_paths:
- config/
- db/
- script/
- spec/
- vendor/
