# make modifications to SCSS Lint rules here.
# See https://github.com/brigade/scss-lint/blob/master/config/default.yml for default configuration.

scss_files: 'app/assets/stylesheets/**/*.scss'

exclude: 'app/assets/stylesheets/vendor/**'

linters:

  BorderZero:
    enabled: true
    convention: zero

  ColorKeyword:
    enabled: true

  ColorVariable:
    enabled: true

  Comment:
    enabled: true
    style: silent

  DeclarationOrder:
    enabled: true

  EmptyLineBetweenBlocks:
    enabled: false

  FinalNewline:
    enabled: false

  HexNotation:
    enabled: false

  IdSelector:
    enabled: false

  ImportantRule:
    enabled: false

  Indentation:
    enabled: false

  LeadingZero:
    enabled: false

  MergeableSelector:
    enabled: false

  NameFormat:
    enabled: false

  NestingDepth:
    enabled: false

  PlaceholderInExtend:
    enabled: false

  PropertySortOrder:
    enabled: false

  PseudoElement:
    enabled: false

  QualifyingElement:
    enabled: false

  SelectorDepth:
    enabled: false

  SelectorFormat:
    enabled: false

  Shorthand:
    enabled: false

  SingleLinePerSelector:
    enabled: false

  SpaceAfterPropertyColon:
    enabled: false

  SpaceAroundOperator:
    enabled: false

  SpaceBeforeBrace:
    enabled: false

  StringQuotes:
    enabled: false

  TrailingSemicolon:
    enabled: false

  TrailingWhitespace:
    enabled: false

  UnnecessaryMantissa:
    enabled: false

  VendorPrefix:
    enabled: false

  ZeroUnit:
    enabled: false
