# make modifications to SCSS Lint rules here.
# See https://github.com/brigade/scss-lint/blob/master/config/default.yml for default configuration.

scss_files: 'app/assets/stylesheets/**/*.scss'

exclude: 'app/assets/stylesheets/vendor/**'

linters:

  BorderZero:
    enabled: false

  ColorKeyword:
    enabled: false

  ColorVariable:
    enabled: false

  Comment:
    enabled: false

  DeclarationOrder:
    enabled: false

  EmptyLineBetweenBlocks:
    enabled: false

  FinalNewline:
    enabled: false

  HexNotation:
    enabled: false

  IdSelector:
    enabled: false

  ImportantRule:
    enabled: false

  Indentation:
    enabled: true
    allow_non_nested_indentation: false
    character: space
    width: 2

  LeadingZero:
    enabled: true
    style: exclude_zero

  MergeableSelector:
    enabled: true
    force_nesting: true

  NameFormat:
    enabled: true
    allow_leading_underscore: false
    convention: hyphenated_lowercase

  NestingDepth:
    enabled: false

  PlaceholderInExtend:
    enabled: false

  PropertySortOrder:
    enabled: false

  PseudoElement:
    enabled: false

  QualifyingElement:
    enabled: false

  SelectorDepth:
    enabled: false

  SelectorFormat:
    enabled: false

  Shorthand:
    enabled: false

  SingleLinePerSelector:
    enabled: false

  SpaceAfterPropertyColon:
    enabled: false

  SpaceAroundOperator:
    enabled: false

  SpaceBeforeBrace:
    enabled: false

  StringQuotes:
    enabled: false

  TrailingSemicolon:
    enabled: false

  TrailingWhitespace:
    enabled: false

  UnnecessaryMantissa:
    enabled: false

  VendorPrefix:
    enabled: false

  ZeroUnit:
    enabled: false
