# make modifications to SCSS Lint rules here.
# See https://github.com/brigade/scss-lint/blob/master/config/default.yml for default configuration.

scss_files: 'app/assets/stylesheets/**/*.scss'

exclude: 'app/assets/stylesheets/vendor/**'

linters:

  BorderZero:
    enabled: false

  ColorKeyword:
    enabled: false

  ColorVariable:
    enabled: false

  Comment:
    enabled: false

  DeclarationOrder:
    enabled: false

  EmptyLineBetweenBlocks:
    enabled: false

  FinalNewline:
    enabled: false

  HexNotation:
    enabled: false

  IdSelector:
    enabled: false

  ImportantRule:
    enabled: false

  Indentation:
    enabled: true
    allow_non_nested_indentation: false
    character: space
    width: 2

  LeadingZero:
    enabled: true
    style: exclude_zero

  MergeableSelector:
    enabled: true
    force_nesting: true

  NameFormat:
    enabled: true
    allow_leading_underscore: false
    convention: hyphenated_lowercase

  NestingDepth:
    enabled: false
    max_depth: 3
    ignore_parent_selectors: false

  PlaceholderInExtend:
    enabled: false

  PropertySortOrder:
    enabled: false
    ignore_unspecified: false
    min_properties: 2
    separate_groups: false
    order: [
      "display",
      "visibility",
      "float",
      "clear"
    ]

  PseudoElement:
    enabled: true

  QualifyingElement:
    enabled: false
    allow_element_with_attribute: false
    allow_element_with_class: false
    allow_element_with_id: false

  SelectorDepth:
    enabled: false
    max_depth: 3

  SelectorFormat:
    enabled: false
    convention: hyphenated_lowercase

  Shorthand:
    enabled: true
    allowed_shorthands: [1, 2, 3]

  SingleLinePerSelector:
    enabled: true

  SpaceAfterPropertyColon:
    enabled: true
    style: one_space

  SpaceAroundOperator:
    enabled: true
    style: one_space

  SpaceBeforeBrace:
    enabled: true
    style: space
    allow_single_line_padding: false

  StringQuotes:
    enabled: true
    style: single_quotes

  TrailingSemicolon:
    enabled: false

  TrailingWhitespace:
    enabled: false

  UnnecessaryMantissa:
    enabled: false

  VendorPrefix:
    enabled: false

  ZeroUnit:
    enabled: false
