version: '3.7'
services:
  selenium:
    image: selenium/standalone-chrome-debug:3.141.59-krypton
    ports: ['4444:4444', '5900:5900']
    logging:
      driver: none
  redis:
    image: redis:3.0.0
  elastic:
    image: elasticsearch:7.9.1
    environment:
      - discovery.type=single-node
  db:
    image: postgres:9.3.10
    ports:
      - '5432:5432'
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
      - .:/home
  greatminds:
    build: .
    command: bash -c "while !</dev/tcp/db/5432; do sleep 1; done; rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    stdin_open: true
    tty: true
    volumes:
      - greatminds-sync:/home:nocopy
    ports:
      - "3000:3000"
    links:
      - elastic
    depends_on:
      - db
      - redis
      - elastic
      - selenium
    environment:
      - REDIS_URL=redis://redis:6379/0
      - ELASTICSEARCH_URL=elastic://elastic:9200/0
      - SELENIUM_HOST=selenium
      - SELENIUM_PORT=4444
      - TEST_APP_HOST=greatminds
      - TEST_PORT=3000
      - SPREE_USE_PAPERCLIP=true
volumes:
  greatminds-sync:
    external: true
