math:
  - :link: https://www.facebook.com/eurekamathofficial/
    :title: Facebook
  - :link: https://twitter.com/eureka_math
    :title: Twitter
  - :link: https://www.instagram.com/greatmindsed/
    :title: Instagram
english:
  - :link: https://www.facebook.com/witwisdomenglish/
    :title: Facebook
  - :link: https://twitter.com/WitWisdomELA
    :title: Twitter
  - :link: https://www.instagram.com/greatmindsed/
    :title: Instagram
history:
  - :link: https://twitter.com/Alexandria_Plan
    :title: Twitter
  - :link: https://www.instagram.com/greatmindsed/
    :title: Instagram
default:
  - :link: https://www.facebook.com/GreatMindsEd
    :title: Facebook
  - :link: https://twitter.com/GreatMindsEd
    :title: Twitter
  - :link: https://www.instagram.com/greatmindsed/
    :title: Instagram
