marketing_templates:
  -
    name: '50/50 Full-Bleed Image Right'
    content: !xml |
      <section class="row <%= background_color %>-bg">
        <div class="col-sm-6 col-centered-content">
          <div class="vertical-center">
            <h6><%= title %></h6>
            <p><%= body_text %></p>
            <a class="btn btn-default btn-block-xs" href="<%= button_link %>"><%= button_title %></a>
          </div>
        </div>
        <div class="col-sm-6 col-img-full" style="background-image: url('<%= image_url %>')">
        </div>
      </section>

  -
    name: 'Masthead'
    content: !xml |
      <div class="masthead">
        <h1><%= title %></h1>
        <div><%= background_image %></div>
      </div>

  -
    name: '50/50 Small Image'
    content: !xml |
      <div>
        <h1><%= title %></h1>
        <div><%= description %></div>
        <div><%= image %></div>
        <div><%= learn_more_url %></div>
      </div>

  -
    name: 'Three Columns'
    content: !xml |
      <div>
        <h1><%= title_1 %></h1>
        <div><%= description_1 %></div>
        <div><%= learn_more_url_1 %></div>
        <h1><%= title_2 %></h1>
        <div><%= description_2 %></div>
        <div><%= learn_more_url_2 %></div>
        <h1><%= title_3 %></h1>
        <div><%= description_3 %></div>
        <div><%= learn_more_url_3 %></div>
      </div>

  -
    name: '50/50 Large Image'
    content: !xml |
      <div>
        <h1><%= title %></h1>
        <div><%= description %></div>
        <div><%= image %></div>
        <div><%= learn_more_url %></div>
        <div><%= download_url %></div>
      </div>

