marketing_templates:
  -
    name: 'Video Hero'
    content: !xml |
      <section class="row img-full image-bg" style="background-image: url('<%= background_image_url %>')">
      	<div class="col-xs-12 col-lg-10 col-lg-offset-1">
      		<div>
      			<h3 class="video-title"><%= title %></h3>
      			<div class="embed-responsive embed-responsive-16by9">
      				<video class="mejs-player" src="<%= video_url %>" width="100%" max-width="850" height="100%""></video>
      			</div>
      		</div>
      	</div>
      </section>

  -
    name: '50/50 Full-Bleed Image Left'
    content: !xml |
      <section class="row <%= background_color %>-bg">
        <div class="col-sm-6 col-img-full" style="background-image: url('<%= image_url %>')">
        </div>
        <div class="col-sm-6 col-centered-content">
          <div class="vertical-center">
            <h6><%= title %></h6>
            <p><%= body_text %></p>
            <% if button_1_title.present? && button_1_link.present? %>
              <a class="btn btn-default btn-block-xs margin-bottom-m" href="<%= button_1_link %>"><%= button_1_title %></a>
            <% end %>
            <% if button_2_title.present? && button_2_link.present? %>
              <a class="btn btn-default btn-block-xs margin-bottom-m" href="<%= button_2_link %>"><%= button_2_title %></a>
            <% end %>
          </div>
        </div>
      </section>

  -
    name: '50/50 Full-Bleed Image Right'
    content: !xml |
      <section class="row <%= background_color %>-bg">
        <div class="col-sm-6 col-centered-content">
          <div class="vertical-center">
            <h6><%= title %></h6>
            <p><%= body_text %></p>
            <% if button_title.present? && button_link.present? %>
              <a class="btn btn-default btn-block-xs" href="<%= button_link %>"><%= button_title %></a>
            <% end %>
          </div>
        </div>
        <div class="col-sm-6 col-img-full" style="background-image: url('<%= image_url %>')">
        </div>
      </section>

  -
    name: '50/50 Content Image Left'
    content: !xml |
      <section class="row <%= background_color %>-bg">
        <div class="col-sm-6 col-centered-content">
          <div class="vertical-center">
            <img src="<%= image_url %>" class="img-responsive img-book margin-sm-bottom-xl">
          </div>
        </div>
        <div class="col-sm-6 col-centered-content">
          <div class="vertical-center">
            <h6><%= title %></h6>
            <p><%= body_text %></p>
            <% if button_title.present? && button_link.present? %>
              <a class="btn btn-default btn-block-xs" href="<%= button_link %>"><%= button_title %></a>
            <% end %>
          </div>
        </div>
      </section>

  -
    name: '50/50 Content Image Right'
    content: !xml |
      <section class="row <%= background_color %>-bg">
        <div class="col-sm-6 col-centered-content">
          <div class="vertical-center">
            <img src="<%= image_url %>" class="img-responsive img-book margin-sm-bottom-xl">
          </div>
        </div>
        <div class="col-sm-6 col-centered-content">
          <div class="vertical-center">
            <h6><%= title %></h6>
            <p><%= body_text %></p>
            <% if button_title.present? && button_link.present? %>
              <a class="btn btn-default btn-block-xs" href="<%= button_link %>"><%= button_title %></a>
            <% end %>
          </div>
        </div>
      </section>

  -
    name: '50/50 Content Image Shadow Left'
    content: !xml |
      <section class="row <%= background_color %>-bg">
        <div class="col-sm-6 col-centered-content">
          <div class="vertical-center">
            <img src="<%= image_url %>" class="img-responsive img-book margin-sm-bottom-xl">
          </div>
        </div>
        <div class="col-sm-6 col-centered-content">
          <div class="vertical-center">
            <h6><%= title %></h6>
            <p><%= body_text %></p>
            <% if button_title.present? && button_link.present? %>
              <a class="btn btn-default btn-block-xs" href="<%= button_link %>"><%= button_title %></a>
            <% end %>
          </div>
        </div>
      </section>

  -
    name: '50/50 Content Image Shadow Right'
    content: !xml |
      <section class="row <%= background_color %>-bg">
        <div class="col-sm-6 col-centered-content">
          <div class="vertical-center">
            <img src="<%= image_url %>" class="img-responsive img-book margin-sm-bottom-xl">
          </div>
        </div>
        <div class="col-sm-6 col-centered-content">
          <div class="vertical-center">
            <h6><%= title %></h6>
            <p><%= body_text %></p>
            <% if button_title.present? && button_link.present? %>
              <a class="btn btn-default btn-block-xs" href="<%= button_link %>"><%= button_title %></a>
            <% end %>
          </div>
        </div>
      </section>

  -
    name: '50/50 Content Image Book Left'
    content: !xml |
      <section class="row <%= background_color %>-bg">
        <div class="col-sm-6 col-centered-content">
          <div class="vertical-center">
            <img src="<%= image_url %>" class="img-responsive img-book margin-sm-bottom-xl">
          </div>
        </div>
        <div class="col-sm-6 col-centered-content">
          <div class="vertical-center">
            <h6><%= title %></h6>
            <p><%= body_text %></p>
            <% if button_title.present? && button_link.present? %>
              <a class="btn btn-default btn-block-xs" href="<%= button_link %>"><%= button_title %></a>
            <% end %>
          </div>
        </div>
      </section>

  -
    name: '50/50 Content Image Book Right'
    content: !xml |
      <section class="row <%= background_color %>-bg">
        <div class="col-sm-6 col-centered-content">
          <div class="vertical-center">
            <img src="<%= image_url %>" class="img-responsive img-book margin-sm-bottom-xl">
          </div>
        </div>
        <div class="col-sm-6 col-centered-content">
          <div class="vertical-center">
            <h6><%= title %></h6>
            <p><%= body_text %></p>
            <% if button_title.present? && button_link.present? %>
              <a class="btn btn-default btn-block-xs" href="<%= button_link %>"><%= button_title %></a>
            <% end %>
          </div>
        </div>
      </section>

  -
    name: 'Image Background, Text Left'
    content: !xml |
      <section class="row row-img-full image-bg" style="background-image: url('<%= image_url %>')">
        <div class="row-img-full-content">
          <div class="col-sm-6 col-centered-content">
            <div class="vertical-center">
              <h6><%= title %></h6>
              <p><%= body_text %></p>
              <% if button_title.present? && button_link.present? %>
                <a class="btn btn-default btn-block-xs margin-bottom-s" href="<%= button_link %>"><%= button_title %></a>
              <% end %>
            </div>
          </div>
        </div>
      </section>

    -
      name: 'Image Background, Text Right'
      content: !xml |
        <section class="row <%= background_color %>-bg">
          <div class="col-sm-6 col-centered-content">
            <div class="vertical-center">
              <img src="<%= image_url %>" class="img-responsive img-book margin-sm-bottom-xl">
            </div>
          </div>
          <div class="col-sm-6 col-centered-content">
            <div class="vertical-center">
              <h6><%= title %></h6>
              <p><%= body_text %></p>
              <% if button_title.present? && button_link.present? %>
                <a class="btn btn-default btn-block-xs" href="<%= button_link %>"><%= button_title %></a>
              <% end %>
            </div>
          </div>
        </section>

  -
    name: 'Full Width Text'
    content: !xml |
      <section class="row <%= background_color %>-bg">
        <div class="col-sm-12 col-lg-6 col-lg-offset-3">
          <h6><%= title %></h6>
          <p><%= body_text %></p>
          <% if button_title.present? && button_link.present? %>
            <a class="btn btn-default btn-block-xs" href="<%= button_link %>"><%= button_title %></a>
          <% end %>
        </div>
      </section>

  -
    name: '3-Column Text'
    content: !xml |
      <section class="row <%= background_color %>-bg">
        <div class="col-sm-4">
          <h6><%= title_1 %></h6>
          <p><%= body_text_1 %></p>
          <% if button_title_1.present? && button_link_1.present? %>
            <a class="btn btn-default btn-block-xs" href="<%= button_link_1 %>"><%= button_title_1 %></a>
          <% end %>
        </div>
        <div class="col-sm-4">
          <h6><%= title_2 %></h6>
          <p><%= body_text_2 %></p>
          <% if button_title_2.present? && button_link_2.present? %>
            <a class="btn btn-default btn-block-xs" href="<%= button_link_2 %>"><%= button_title_2 %></a>
          <% end %>
        </div>
        <div class="col-sm-4">
          <h6><%= title_3 %></h6>
          <p><%= body_text_3 %></p>
          <% if button_title_3.present? && button_link_3.present? %>
            <a class="btn btn-default btn-block-xs" href="<%= button_link_3 %>"><%= button_title_3 %></a>
          <% end %>
        </div>
      </section>
