marketing_templates:
  -
    name: 'Role/Curriculum Selector Hero'
    content: !xml |
      <div class="row intro masthead" style="background-image: url('<%= background_image_url %>')">
        <div class="col-xs-12 masthead-content text-center">
          <h5 class="home-mast-intro bold"><%= title %></h5>
          <div id="pageSelection">
            <div class="btn-group fixed-width image-background">
              <button class="btn btn-default btn-block-xs margin-sm-bottom-m dropdown-toggle" type="button" id="dropdownRole" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                I am a
                <span class="caret"></span>
              </button>
              <ul class="dropdown-menu" aria-labelledby="dropdownRole">
                <li><a href="#">Teacher</a></li>
                <li><a href="#">Parent</a></li>
                <li><a href="#">Administrator</a></li>
              </ul>
            </div>
            <div class="btn-group fixed-width image-background">
              <button class="btn btn-default btn-block-xs margin-sm-bottom-m dropdown-toggle" type="button" id="dropdownCurriculum" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                Looking into
                <span class="caret"></span>
              </button>
              <ul class="dropdown-menu" aria-labelledby="dropdownCurriculum">
                <li><a href="#">Math</a></li>
                <li><a href="#">English</a></li>
                <li><a href="#">History</a></li>
              </ul>
            </div>
            <a href="#" id="btnGo" class="btn btn-default btn-transparent btn-block-xs margin-sm-bottom-m" disabled="disabled">Go</a>
          </div>
        </div>
      </div>
      <script type="text/javascript">
        $(function() {
          $('select#role').change(function(e){
            goToPage();
          });
          $('select#curriculum').change(function(e){
            goToPage();
          });

          function goToPage(){
            var role = $('select#role').val();
            var curriculumId = $('select#curriculum').val();
            if ( role && curriculumId ) {
              var url = "/decide_page_to_go?" + $.param({role: role, curriculum_id: curriculumId});
              window.location.href = url;
            };
          }
        });
      </script>

  -
    name: 'Video Hero'
    content: !xml |
      <section class="row row-video-hero" style="background-image: url('<%= background_image_url %>')">
        <div class="col-xs-12">
          <h3 class="video-title"><%= title %></h3>
          <div class="embed-responsive embed-responsive-16by9">
            <video class="mejs-player" src="<%= video_url %>" width="100%" max-width="850" height="100%"></video>
          </div>
        </div>
      </section>

  -
    name: '50/50 Full-Bleed Image Left'
    content: !xml |
      <section class="row <%= background_color %>-bg">
        <div class="col-sm-6 col-img-full" style="background-image: url('<%= image_url %>')">
        </div>
        <div class="col-sm-6 col-centered-content">
          <div class="vertical-center">
            <h6><%= title %></h6>
            <p><%= body_text %></p>
            <% if button_1_title.present? && button_1_link.present? %>
              <a class="btn btn-default btn-block-xs margin-bottom-m" href="<%= button_1_link %>"><%= button_1_title %></a>
            <% end %>
            <% if button_2_title.present? && button_2_link.present? %>
              <a class="btn btn-default btn-block-xs margin-bottom-m" href="<%= button_2_link %>"><%= button_2_title %></a>
            <% end %>
          </div>
        </div>
      </section>

  -
    name: '50/50 Full-Bleed Image Right'
    content: !xml |
      <section class="row <%= background_color %>-bg">
        <div class="col-sm-6 col-centered-content">
          <div class="vertical-center">
            <h6><%= title %></h6>
            <p><%= body_text %></p>
            <% if button_title.present? && button_link.present? %>
              <a class="btn btn-default btn-block-xs" href="<%= button_link %>"><%= button_title %></a>
            <% end %>
          </div>
        </div>
        <div class="col-sm-6 col-img-full" style="background-image: url('<%= image_url %>')">
        </div>
      </section>

  -
    name: '50/50 Content Image Left'
    content: !xml |
      <section class="row <%= background_color %>-bg">
        <div class="col-sm-6 col-centered-content">
          <div class="vertical-center">
            <img src="<%= image_url %>" class="img-responsive margin-sm-bottom-xl">
          </div>
        </div>
        <div class="col-sm-6 col-centered-content">
          <div class="vertical-center">
            <h6><%= title %></h6>
            <p><%= body_text %></p>
            <% if button_title.present? && button_link.present? %>
              <a class="btn btn-default btn-block-xs" href="<%= button_link %>"><%= button_title %></a>
            <% end %>
          </div>
        </div>
      </section>

  -
    name: '50/50 Content Image Right'
    content: !xml |
      <section class="row <%= background_color %>-bg">
        <div class="col-sm-6 col-centered-content">
          <div class="vertical-center">
            <h6><%= title %></h6>
            <p><%= body_text %></p>
            <% if button_title.present? && button_link.present? %>
              <a class="btn btn-default btn-block-xs" href="<%= button_link %>"><%= button_title %></a>
            <% end %>
          </div>
        </div>
        <div class="col-sm-6 col-centered-content">
          <div class="vertical-center">
            <img src="<%= image_url %>" class="img-responsive">
          </div>
        </div>
      </section>

  -
    name: '50/50 Content Image Shadow Left'
    content: !xml |
      <section class="row <%= background_color %>-bg">
        <div class="col-sm-6 col-centered-content">
          <div class="vertical-center">
            <img src="<%= image_url %>" class="img-responsive img-shadow margin-sm-bottom-xl">
          </div>
        </div>
        <div class="col-sm-6 col-centered-content">
          <div class="vertical-center">
            <h6><%= title %></h6>
            <p><%= body_text %></p>
            <% if button_title.present? && button_link.present? %>
              <a class="btn btn-default btn-block-xs" href="<%= button_link %>"><%= button_title %></a>
            <% end %>
          </div>
        </div>
      </section>

  -
    name: '50/50 Content Image Shadow Right'
    content: !xml |
      <section class="row <%= background_color %>-bg">
        <div class="col-sm-6 col-centered-content">
          <div class="vertical-center">
            <h6><%= title %></h6>
            <p><%= body_text %></p>
            <% if button_title.present? && button_link.present? %>
              <a class="btn btn-default btn-block-xs" href="<%= button_link %>"><%= button_title %></a>
            <% end %>
          </div>
        </div>
        <div class="col-sm-6 col-centered-content">
          <div class="vertical-center">
            <img src="<%= image_url %>" class="img-responsive img-shadow">
          </div>
        </div>
      </section>

  -
    name: '50/50 Content Image Book Left'
    content: !xml |
      <section class="row <%= background_color %>-bg">
        <div class="col-sm-6 col-centered-content">
          <div class="vertical-center">
            <img src="<%= image_url %>" class="img-responsive img-book margin-sm-bottom-xl">
          </div>
        </div>
        <div class="col-sm-6 col-centered-content">
          <div class="vertical-center">
            <h6><%= title %></h6>
            <p><%= body_text %></p>
            <% if button_title.present? && button_link.present? %>
              <a class="btn btn-default btn-block-xs" href="<%= button_link %>"><%= button_title %></a>
            <% end %>
          </div>
        </div>
      </section>

  -
    name: '50/50 Content Image Book Right'
    content: !xml |
      <section class="row <%= background_color %>-bg">
        <div class="col-sm-6 col-centered-content">
          <div class="vertical-center">
            <h6><%= title %></h6>
            <p><%= body_text %></p>
            <% if button_title.present? && button_link.present? %>
              <a class="btn btn-default btn-block-xs" href="<%= button_link %>"><%= button_title %></a>
            <% end %>
          </div>
        </div>
        <div class="col-sm-6 col-centered-content">
          <div class="vertical-center">
            <img src="<%= image_url %>" class="img-responsive img-book">
          </div>
        </div>
      </section>

  -
    name: 'Image Background, Full Width Text'
    content: !xml |
      <section class="row row-img-full row-content-full" style="background-image: url('<%= image_url %>')">
        <div class="row-img-full-content">
          <div class="col-sm-12 col-centered-content">
            <div class="vertical-center">
              <h6><%= title %></h6>
              <p><%= body_text %></p>
              <% if button_title.present? && button_link.present? %>
                <a class="btn btn-default btn-block-xs margin-bottom-s" href="<%= button_link %>"><%= button_title %></a>
              <% end %>
            </div>
          </div>
        </div>
      </section>

  -
    name: 'Image Background, Text Left'
    content: !xml |
      <section class="row row-img-full" style="background-image: url('<%= image_url %>')">
        <div class="row-img-full-content">
          <div class="col-sm-6 col-centered-content">
            <div class="vertical-center">
              <h6><%= title %></h6>
              <p><%= body_text %></p>
              <% if button_title.present? && button_link.present? %>
                <a class="btn btn-default btn-block-xs margin-bottom-s" href="<%= button_link %>"><%= button_title %></a>
              <% end %>
            </div>
          </div>
          <div class="col-sm-6"></div>
        </div>
      </section>

  -
    name: 'Image Background, Text Right'
    content: !xml |
      <section class="row row-img-full" style="background-image: url('<%= image_url %>')">
        <div class="row-img-full-content">
          <div class="col-sm-6"></div>
          <div class="col-sm-6 col-centered-content">
            <div class="vertical-center">
              <h6><%= title %></h6>
              <p><%= body_text %></p>
              <% if button_title.present? && button_link.present? %>
                <a class="btn btn-default btn-block-xs margin-bottom-s" href="<%= button_link %>"><%= button_title %></a>
              <% end %>
            </div>
          </div>
        </div>
      </section>

  -
    name: 'Full Width Text'
    content: !xml |
      <section class="row row-content-full <%= background_color %>-bg">
        <div class="col-sm-12">
          <h6><%= title %></h6>
          <p><%= body_text %></p>
          <% if button_title.present? && button_link.present? %>
            <a class="btn btn-default btn-block-xs" href="<%= button_link %>"><%= button_title %></a>
          <% end %>
        </div>
      </section>

  -
    name: '2-Column Text'
    content: !xml |
      <section class="row row-content-2col">
        <div class="col-sm-6 col-centered-content <%= background_color_1 %>-bg">
          <div class="vertical-center">
            <h6><%= title_1 %></h6>
            <p><%= body_text_1 %></p>
            <% if button_title_1.present? && button_link_1.present? %>
              <a class="btn btn-default btn-block-xs" href="<%= button_link_1 %>"><%= button_title_1 %></a>
            <% end %>
          </div>
        </div>
        <div class="col-sm-6 col-centered-content <%= background_color_2 %>-bg">
          <div class="vertical-center">
            <h6><%= title_2 %></h6>
            <p><%= body_text_2 %></p>
            <% if button_title_2.present? && button_link_2.present? %>
              <a class="btn btn-default btn-block-xs" href="<%= button_link_2 %>"><%= button_title_2 %></a>
            <% end %>
          </div>
        </div>
      </section>

  -
    name: '2-Column Video Left, Text Right'
    content: !xml |
      <section class="row row-img-full row-video-left" style="background-image: url('<%= background_image_url %>')">
        <div class="row-img-full-content">
          <div class="col-sm-6 col-centered-content margin-sm-bottom-xl">
            <div class="vertical-center">
              <div class="embed-responsive embed-responsive-16by9">
                <video class="mejs-player" src="<%= video_url %>" width="100%" max-width="850" height="100%"></video>
              </div>
            </div>
          </div>
          <div class="col-sm-6 col-centered-content">
            <div class="vertical-center">
              <h6><%= title %></h6>
              <p><%= body_text %></p>
              <% if button_title.present? && button_link.present? %>
                <a class="btn btn-default btn-block-xs" href="<%= button_link %>"><%= button_title %></a>
              <% end %>
            </div>
          </div>
        </div>
      </section>

  -
    name: '3-Column Text'
    content: !xml |
      <section class="row row-content-3col <%= background_color %>-bg">
        <div class="col-sm-4">
          <h6><%= title_1 %></h6>
          <p><%= body_text_1 %></p>
          <% if button_title_1.present? && button_link_1.present? %>
            <a class="btn btn-default btn-block-xs" href="<%= button_link_1 %>"><%= button_title_1 %></a>
          <% end %>
        </div>
        <div class="col-sm-4">
          <h6><%= title_2 %></h6>
          <p><%= body_text_2 %></p>
          <% if button_title_2.present? && button_link_2.present? %>
            <a class="btn btn-default btn-block-xs" href="<%= button_link_2 %>"><%= button_title_2 %></a>
          <% end %>
        </div>
        <div class="col-sm-4">
          <h6><%= title_3 %></h6>
          <p><%= body_text_3 %></p>
          <% if button_title_3.present? && button_link_3.present? %>
            <a class="btn btn-default btn-block-xs" href="<%= button_link_3 %>"><%= button_title_3 %></a>
          <% end %>
        </div>
      </section>
