History:
  !xml |
  <a class="twitter-timeline" href="https://twitter.com/GreatMindsEd/lists/history" data-widget-id="652520570781761536" data-chrome="noheader">Tweets from https://twitter.com/GreatMindsEd/lists/history</a>
  <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

English:
  !xml |
  <a class="twitter-timeline" href="https://twitter.com/GreatMindsEd/lists/english" data-widget-id="652520737182318592" data-chrome="noheader">Tweets from https://twitter.com/GreatMindsEd/lists/english</a>
  <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

Math:
  !xml |
  <a class="twitter-timeline" href="https://twitter.com/GreatMindsEd/lists/math" data-widget-id="652520868245975040" data-chrome="noheader">Tweets from https://twitter.com/GreatMindsEd/lists/math</a>
  <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

English_History_Math:
  !xml |
  <a class="twitter-timeline" href="https://twitter.com/GreatMindsEd/lists/math-history-english" data-widget-id="652519954227462145" data-chrome="noheader">Tweets from https://twitter.com/GreatMindsEd/lists/math-history-english</a>
  <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

History_Math:
  !xml |
  <a class="twitter-timeline" href="https://twitter.com/GreatMindsEd/lists/math-history" data-widget-id="652520163959402496" data-chrome="noheader">Tweets from https://twitter.com/GreatMindsEd/lists/math-history</a>
  <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

English_History:
  !xml |
  <a class="twitter-timeline" href="https://twitter.com/GreatMindsEd/lists/history-english" data-widget-id="652520310667784192" data-chrome="noheader">Tweets from https://twitter.com/GreatMindsEd/lists/history-english</a>
  <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

English_Math:
  !xml |
  <a class="twitter-timeline" href="https://twitter.com/GreatMindsEd/lists/math-english" data-widget-id="652520444122165248" data-chrome="noheader">Tweets from https://twitter.com/GreatMindsEd/lists/math-english</a>
  <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
