name: Deploy Dev App 
on:
  push:
    branches:
      - feature/upgrade-rails-ruby

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: checkot the code 
      uses: actions/checkout@v2
      with:
          ref: feature/upgrade-rails-ruby
    - name: setup ruby 
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6
    - uses: miloserdow/capistrano-deploy@v1.3
      with:
        target: dev
        deploy_key: ${{ secrets.cds_dev_ssh_key }}

